[book]
authors = ["System76"]
language = "en"
multilingual = false
src = "docs"
title = "Pop!_Docs"

[build]
create-missing = false
use-default-preprocessors = false
build-dir = "static/docs"

[output.html]
theme = "static"
additional-css = ["static/docs.css", "static/minimal.common.css"]
git-repository-url = "https://github.com/pop-os/website"
git-repository-icon = "fa-github"